### ISSUE TITLE
Decide which "motivational quotes" API to use to encourage people to complete their 100daysofcode journey.

### ISSUE THREAD

**Issue by renners7777** [drewlearns/100daysofcode_reminder_app#11]
When users log in to their dashboard, it would be really great to have a motivational quote appear at the top of the page to encourage people before they record their daily coding work. So I suggest we find an API that produces a random quote each time the user logs in. There are loads of APIs to choose from so I have added three which came to the top of my Google search below.

**Comment by renners7777** [comment]
https://zenquotes.io/ 

https://api-ninjas.com/api/quotes 

https://rapidapi.com/collection/quote-generator-apis

**Comment by renners7777** [comment]
Hi all. I've created a motivational quote API, which would work quite well I think with our project. You can see it at https://renners7777.github.io/motivationalQuotesAPI/
Check it out and let me know whether it would work or not. I know that we are still at the start of this process but thought I would try to get some features working anyway.

**Comment by drewlearns** [comment]
That will probably work
