### ISSUE TITLE
Readme Creation

### ISSUE THREAD

**Issue by drewlearns** [drewlearns/100daysofcode_reminder_app#2]

**Comment by renners7777** [comment]
I'll get started re-vamping the Readme we used in the first webpage we started creating at OS_100days.

**Comment by renners7777** [comment]
Please have a read of the README and let me know whether it needs any changes. It might be best to leave this issue open until we have finished the project?

**Comment by drewlearns** [comment]
I think the readme should be a living breathing document. Hopefully eventually, before any pull request is approved the last updated date field on it gets updated at the very least to allow readers to know it's fresh and maintained.
