### ISSUE TITLE
Wire Frame UI/UX design

### ISSUE THREAD

**Issue by drewlearns** [drewlearns/100daysofcode_reminder_app#3]

**Comment by renners7777** [comment]
In our meeting yesterday (Google Meet event) we talked through this issue and said the following:
 - we would benefit from a UI/UX designer joining us on this project as myself and D-KILLJOY have limited design experience although we know our basic design principles and how to make websites using HTML and CSS. 
 - Drew suggested someone might use Figma or similar design websites to sketch up some samples of what the site might look like. 
 - We will need a sign-up/login front page, a login page will take you to your dashboard to input what coding you have done that day (100daysofcode challenge), and we will possibly also have links to separate HTML pages where people will be able to read the license, etc. We will probably want an About page too. When logging out, users should be taken back to the login screen again. 

It would be great to hear (and see) people's design ideas in this section, even if they are only hand-drawn (no judgment here).

**Comment by drewlearns** [comment]
I think the consensus is that we are going to use pen and paper for a rough outline but if we find a UI/UX designer looking to contribute to an opensource project it would be a great issue to work on in figma since we are all not familiar with the tool

**Comment by Hyperi0nGit** [comment]
So far I've done all my wireframing as an individual I haven't tried collaborative wireframing before. So moving forward is the plan to each draw up wire frame diagrams & present them then decide as a group on what features to keep? how do we plan to do this?

**Comment by renners7777** [comment]
Can I suggest we bring our ideas along to Mondays meet up event to discuss them there? Either that or I can arrange an event for us to meet before that. Perhaps tomorrow?

**Comment by Hyperi0nGit** [comment]
![Screenshot at 2023-02-14 11-22-50](https://user-images.githubusercontent.com/108790200/218588231-edc8d1c7-113d-4479-bd65-55c9dd3fb231.png)

**Comment by renners7777** [comment]
We could possibly use a modal for the "sign-up" section rather than a separate page?

**Comment by Hyperi0nGit** [comment]
Came across this on LinkedIN - May be of use to us:
[Log in.pdf](https://github.com/drewlearns/100daysofcode_reminder_app/files/10821403/Log.in.pdf)
