### ISSUE TITLE
Licensing research and creation for the opensource project

### ISSUE THREAD

**Issue by drewlearns** [drewlearns/100daysofcode_reminder_app#4]

**Comment by Hyperi0nGit** [comment]
https://opensource.org/licenses - I found this about OpenSource Licences

https://github.com/licenses/license-templates - GitHub Licence Templates

https://opensource.stackexchange.com/questions/5599/any-successful-dual-license-oss-project-i-can-use-as-template - self reading reference
https://en.wikipedia.org/wiki/Contributor_License_Agreement - reference for CA (warning - wikipedia)

**Comment by renners7777** [comment]
> https://opensource.org/licenses - I found this about OpenSource Licences
> 
> https://github.com/licenses/license-templates - GitHub Licence Templates
> 
> https://opensource.stackexchange.com/questions/5599/any-successful-dual-license-oss-project-i-can-use-as-template - self reading reference https://en.wikipedia.org/wiki/Contributor_License_Agreement - reference for CA (warning - wikipedia)

Hi BBWeb3. We already have the basic MIT licence but by all means if you feel there is a more appropriate licence for this project please let us know.

**Comment by Hyperi0nGit** [comment]
I saw that MIT licence Chris - that will be all good IMO. Given that it's not being sold for commercial gain, do we need to worry about Contributor Licence? I can't foresee any Copy-write disputes.  @drewlearns @renners7777

**Comment by drewlearns** [comment]
I'm really no expert here but I think an MIT license is the way to go from the templates is good from what I do know.
