### ISSUE TITLE
Twitter API Research 

### ISSUE THREAD

**Issue by drewlearns** [drewlearns/100daysofcode_reminder_app#5]

**Comment by Hyperi0nGit** [comment]
https://www.youtube.com/watch?v=T_K9Zs9s9B0 - Twitter Search API example + ReactNative

https://www.youtube.com/watch?v=qu_4rmvpS5k&t=4s - Basic Intro to Twitter APIs

https://buffer.com/library/free-twitter-tools/ - Big Library of Interesting Twitter Apps - Examples

**Comment by renners7777** [comment]
https://developer.twitter.com/en/docs/twitter-api - to find out more about twitter apis
